---

- hosts: incron_server
#  become: true

  roles:
   - role: incron
     incron_system_tables:
       - name: incron_test
         path: /home/vagrant/incron_test
         mask: IN_CREATE 
         command: touch /home/newfile
