---
- name: Add epel in Centos
  yum: name=epel-release state=present

- name: Updating cache ...
  yum: name=* state=latest

- name: Install incron in Centos
  yum: name=incron state=present
<<<<<<< HEAD

- name: Check that the /etc/incron.allow file exists
  stat:
    path: /etc/incron.allow
  register: stat_result

- name: Create the file, if it doesnt exist already
  file:
    path: /etc/incron.allow
    state: touch
  when: stat_result.stat.exists == False 
=======
>>>>>>> a5897f45799d4ee4b73c4e670636b44eb46dce11

- name: Ensure Incron is running and enabled as configured.
  service:
    name: "{{ incron_daemond }}"
    state: started
    enabled: yes
  when: incron_enabled

- name: Ensure Incron is stopped and disabled as configured.
  service:
    name: "{{ incron_daemond }}"
    state: stopped
    enabled: no
  when: not incron_enabled

