---
# handlers file for incron
- name: restart incron
  service: "name={{ incron_daemon }} state=restarted"
  when: incron_enabled

- name: restart incrond
  service: "name={{ incron_daemond }} state=restarted"
  when: incron_enabled
